name: Scriveqa Cypress Tests

on: [ workflow_dispatch ]

jobs:
  cypress-run-chrome:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          record: true
        env: 
          CYPRESS_RECORD_KEY: f665f078-4cb5-492f-8136-e2d193ac563f
          
  cypress-run-electron:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          browser: electron
          record: true
        env: 
          CYPRESS_RECORD_KEY: f665f078-4cb5-492f-8136-e2d193ac563f

       
  cypress-run-edge:
    runs-on: ubuntu-latest
    container: cypress/browsers:node16.16.0-chrome107-ff107-edge
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          browser: edge
          env: false
          
  cypress-run-firefox:
    runs-on: ubuntu-latest
    container:
        image: cypress/browsers:node13.6.0-chrome80-ff72
        options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          browser: firefox
          env: false
