name: Scriveqa Cypress Tests

on: [ workflow_dispatch ]

jobs:
  cypress-run-chrome:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          env: false
      - run: npx cypress run --record --key f665f078-4cb5-492f-8136-e2d193ac563f  
  cypress-run-firefox:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Firefox
        uses: ./
        timeout-minutes: 3
        with:
          # let's show browser and system info
          build: npx cypress info
          working-directory: examples/v10/firefox
          browser: firefox

      # report screenshot size and store the screenshots as test artifacts
      - uses: actions/upload-artifact@v3
        with:
          name: screenshots-in-firefox
          path: examples/v10/firefox/cypress/screenshots

      - run: npx image-size cypress/screenshots/**/*.png
        working-directory: examples/v10/firefox
        
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          browser: firefox
          env: false
      - run: npx cypress run --record --key f665f078-4cb5-492f-8136-e2d193ac563f  
       
  cypress-run-edge:
    runs-on: ubuntu-latest
    container: cypress/browsers:node16.16.0-chrome107-ff107-edge
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          browser: edge
          env: false
      - run: npx cypress run --record --key f665f078-4cb5-492f-8136-e2d193ac563f  
